language: node_js

node_js:
   - node

branches:
   only:
      - master

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:
   - npm install -g --silent @angular/cli

jobs:
  include:
    - stage: Build
      script: ng build --prod
    - stage: Test
      script: ng test --watch false

notifications:
  email:
    on_failure: change
    on_success: change  